
if (FMI4CPP_LOG_LEVEL STREQUAL "OFF")
  target_compile_definitions(fmi4cpp PRIVATE MLOG_LEVEL_OFF)
elseif (FMI4CPP_LOG_LEVEL STREQUAL "TRACE")
  target_compile_definitions(fmi4cpp PRIVATE MLOG_LEVEL_TRACE)
elseif (FMI4CPP_LOG_LEVEL STREQUAL "DEBUG")
  target_compile_definitions(fmi4cpp PRIVATE MLOG_LEVEL_DEBUG)
elseif (FMI4CPP_LOG_LEVEL STREQUAL "INFO")
  target_compile_definitions(fmi4cpp PRIVATE MLOG_LEVEL_INFO)
elseif (FMI4CPP_LOG_LEVEL STREQUAL "WARN")
  target_compile_definitions(fmi4cpp PRIVATE MLOG_LEVEL_WARN)
elseif (FMI4CPP_LOG_LEVEL STREQUAL "ERROR")
  target_compile_definitions(fmi4cpp PRIVATE MLOG_LEVEL_ERROR)
elseif (FMI4CPP_LOG_LEVEL STREQUAL "FATAL")
  target_compile_definitions(fmi4cpp PRIVATE MLOG_LEVEL_FATAL)
else ()
  target_compile_definitions(fmi4cpp PRIVATE $<$<CONFIG:Debug>:MLOG_LEVEL_DEBUG>)
endif ()