
name: C++ CI (apt-get)

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Install tools
      run: |
        sudo apt-get install gcc g++ cmake libzip-dev libboost-dev libboost-filesystem-dev libboost-test-dev
      shell: bash

    - name: Configure
      run: |
        cmake -H. -Bbuild -DFMI4CPP_BUILD_TESTS=ON -DFMI4CPP_BUILD_EXAMPLES=ON -DBUILD_SHARED_LIBS=OFF
      shell: bash

    - name: Build
      run: |
        cmake --build build
      shell: bash

    - name: Test
      run: |
        cd build/tests && ctest
      shell: bash
